use_frameworks!

platform :ios, '8.0'

target 'TYTools_Example' do
  pod 'TYTools', :path => '../'

  target 'TYTools_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
