# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
- xcrun instruments -w 'iPhone 7' || sleep 15
script:
- xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TYTools.xcworkspace -scheme TYTools-Example -destination "name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
