# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
- xcrun instruments -w 'iPhone 7' || sleep 15
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TYTools.xcworkspace -scheme TYTools-Example -destination "name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
